### ISSUE TITLE
Disabling Enchantement still display the new enchantements in the enchanting table

### ISSUE THREAD

**Issue by DaftHunk** [Insane-96/IguanaTweaksReborn#323]
**Versions**:
- Minecraft: 1.20.1
- Forge: 47.2.36
- IguanaTweaks Reborn: 3.21.1
- InsaneLib: 1.15.0

**What Happens**:  
Enchantement config is disabled but still display the new enchantements in the enchanting table :
![2024-11-01_18 50 40](https://github.com/user-attachments/assets/bb463cab-5102-4c22-8648-e0025de1d07d)
(Easy to notice for us as your enchantements are displayed in english instead of french)

**Config**:  
E.g. https://pastebin.com/TfQQeZdy

**Comment by Insane96** [comment]
Fixed for next update, coming really soon

**Comment by Insane96** [comment]
![image](https://github.com/user-attachments/assets/7abdc6b7-dbb3-49b6-95bd-28b3c436befc)
Can't reproduce, will need more info. I've just set "Enable Enchantments" to false and (most) of the enchantments stopped appearing.

I said most because I missed Feather Falling and Luck, they still appear unless "Replace looting, fortune and LotS enchantments" and "Replace protection enchantments" are set to false. But other protections and damaging enchantments work properly when the feature is disabled.

**Comment by DaftHunk** [comment]
Sure what can I provide to you ? Do you want the modpack link ?

**Comment by Insane96** [comment]
Reproduce with the least mods possible. There might be some other mod messing with the enchanting table.

**Comment by DaftHunk** [comment]
I still have the problem with only Iguana Tweaks activated :
![2024-11-08_20 40 29](https://github.com/user-attachments/assets/7b1de8ef-41c5-469f-913d-5dcc73b2712c)
![Capture d’écran 2024-11-08 204105](https://github.com/user-attachments/assets/0a28a838-3a67-4c81-b522-18885ece022d)

**Comment by Insane96** [comment]
Did you change the config or is still the one in the other issue?

**Comment by DaftHunk** [comment]
Still the same, I can reset it to try indeed

**Comment by DaftHunk** [comment]
I have reset it and only disabled "enchantements" but it's still the same :/
https://pastebin.com/9feE9Ze3

**Comment by Insane96** [comment]
![image](https://github.com/user-attachments/assets/581cfed4-bdbc-4d2d-9ed6-b736cbe7c353)
Still can't reproduce with the exact same config. I have diamond swords and golden chestplates with full enchanting table and not a single ITE enchantment pops out.

**Comment by DaftHunk** [comment]
No problem, don't worry I finally removed the mod  
Thanks for your time :)
